@startuml
abstract class Person {
+firstname
-lastname
||
'Kommentar im Code'
}
class Teacher {
#salary
title
}
class Student {
matnr
}

note "Dies hier ist ein Kommentar" as firstComment
firstComment.Person
Person "*" <-- "1" Teacher
Person <-- Student
@enduml